# Generated by Django 5.2.6 on 2025-09-11 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_owner_alter_task_completed_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add host to Event (allow null to avoid default prompts if existing rows)
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events_hosted',
                null=True,
                blank=True,
            ),
        ),
        # Add status to Event
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(
                max_length=16,
                choices=(
                    ('upcoming', 'Upcoming'),
                    ('ongoing', 'Ongoing'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                ),
                default='upcoming',
            ),
        ),
        # Create Invitation (through model for Event.guests)
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    max_length=16,
                    choices=(('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')),
                    default='pending',
                )),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(null=True, blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='todo.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'guest')},
            },
        ),
        # Add Event.guests M2M (through Invitation). No separate table is created beyond Invitation.
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL,
                through='todo.Invitation',
                related_name='events_invited',
            ),
        ),
        # Add Notification.event FK
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(
                to='todo.event',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notifications',
            ),
        ),
    ]
