# Generated by Django 5.2.6 on 2025-09-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_cleanup_assignment_fields'),
        ('todo', '0004_note_owner'),
    ]

    operations = [
    ]
