# Generated by Django 5.2.6 on 2025-09-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_cancelled_status_from_event'),
        ('todo', '0008_alter_event_status'),
        ('todo', '0008_change_completed_to_ended'),
    ]

    operations = [
    ]
